### ISSUE TITLE
Auto-Save Problem

### ISSUE THREAD

**Issue by Sgambe** [thecoder-001/MineColab#28]
Hi, I am trying to enable auto-save because yesterday the server crashed and did some strange things to the saves. I found on the web that I have to edit paper.yml, I did but it still doesn't save. Is there a code snippet to implent in the main code that I can use?

**Comment by yougeshlama** [comment]
same i am having the same problem

**Comment by thecoder-001** [comment]
What did you change in `paper.yml` ?
You can change the value of `autosave` in `bukkit.yml`
```yml
ticks-per: 
   animal-spawns: 400
   monster-spawns: 1
   autosave: 6000 # change this to something lower
```
